services:
  db:
    image: postgres:latest
    container_name: dev_postgres
    restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: handly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
    container_name: handly-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:12345678@db:5432/handly
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
